version: "2.2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: "es-cluster"
    volumes:
      - ./elasticsearch/certs:/usr/share/elasticsearch/config/ssl     #集群内部通信证书
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins      #中文分词插件
    ports:
      - ${ES_PORT}:9200
      - 9300:9300
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=192.168.1.2,192.168.1.3,192.168.1.4
      - discovery.seed_hosts=192.168.1.3,192.168.1.4
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - network.publish_host=192.168.1.2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8192m -Xmx8192m"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/ssl/elasticsearch_key.pem
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/ssl/elasticsearch_cert.pem
    #    mem_limit: ${MEM_LIMIT}
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    restart: always
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_URL=http://es01:9200
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - ELASTICSEARCH_USERNAME=kibana